<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['ipsec_app_description'] = 'The IPsec app provides core system functions for IPsec VPNs';
$lang['ipsec_app_name'] = 'IPsec';
