<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['ipsec_app_description'] = 'Приложение "IPsec" обеспечивает функции ядра системы для IPsec VPN';
$lang['ipsec_app_name'] = 'IPsec';
