<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['ipsec_app_description'] = 'Aplikacja IPsec dostarcza niezbędne funkcje systemowe do obsługi VPN\'ów IPsec';
$lang['ipsec_app_name'] = 'IPsec';
